### ISSUE TITLE
Use Transifex for continuous translation please

### ISSUE THREAD

**Issue by p-bo** [R0Wi-DEV/workflow_ocr#146]
Hello,
would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
...and gain benefits from work of whole Nextcloud translators community for users of your app please?

Thanks :-)

**Comment by R0Wi** [comment]
Thank's for the hint, this was already on my schedule but I didn't have time to implement it, yet. PR would be welcome since I don't know when I'll have time to have a look at it.

**Comment by p-bo** [comment]
Don't worry, it shouldn't take you much time - just open issue on https://github.com/nextcloud/docker-ci/issues/new/choose (choose Request translations). And you will get checklist as for example this: https://github.com/nextcloud/docker-ci/issues/426 and you can ask [rakekniven](https://github.com/rakekniven) if something is unclear to you. Hope it helps :-)

**Comment by p-bo** [comment]
@R0Wi Glad to help and thanks for your attention to this :-)

**Comment by p-bo** [comment]
Foremost - no pressure - just if time will allow to look at it…

**Comment by comradekingu** [comment]
Use https://hosted.weblate.org/hosting/ instead.
Better terms of service, better community, better results, libre software.

**Comment by p-bo** [comment]
@R0Wi just for curiosity - how is it going regarding this please?

**Comment by R0Wi** [comment]
Setup for basic infrastructure is WIP

**Comment by p-bo** [comment]
Great - thanks! :-)

**Comment by R0Wi** [comment]
Closed via https://github.com/nextcloud/docker-ci/issues/518
