### ISSUE TITLE
empty language list in nextcloud 25.0.3

### ISSUE THREAD

**Issue by rodrigoesborges** [R0Wi-DEV/workflow_ocr#183]
First of all,

Thanks for the flow, it intends to fill elegantly such a valuable activity.

In 1.25.0.3, just installed, tried removing and reinstalling, but still no luck in having language options:

![image](https://user-images.githubusercontent.com/3339104/217898737-129ec663-0120-480f-bd22-f769456157b2.png)
Inspecting console:
![image](https://user-images.githubusercontent.com/3339104/217898937-05c43c22-a5f5-4508-90de-6cf43f335347.png)

```
failed to load resource: the server responded with a status of 500 (Internal Server Error)
core-common.js?v=6bad9ade-15:2 Error: Request failed with status code 500
    at t.exports (workflow_ocr-main.js?v=6bad9ade-15:2:502363)
    at t.exports (workflow_ocr-main.js?v=6bad9ade-15:2:504779)
    at XMLHttpRequest.x (workflow_ocr-main.js?v=6bad9ade-15:2:496993)
```
and devtools complains:
` https://coletiva.imperialismoedependencia.org/apps/workflow_ocr/js/workflow_ocr-main.js.map?v=1f44476e4073c3482803: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

Couldn't find a similar issue reported. Any directions?

**Comment by R0Wi** [comment]
Thank's for reporting this. Think you're dacing a serverside error so it would be good to have some lines of your `nextcloud.log` file to see what crashed. As a temporary workaround you could try using the flow without any languages choosen, even though the result might be a bit worse.

**Comment by R0Wi** [comment]
@rodrigoesborges have you already been able to take a look into the logs?

**Comment by rodrigoesborges** [comment]
I will look into it today or, max, tomorrow

**Comment by R0Wi** [comment]
Closed due to lack of information. Please reopen if needed.
