### ISSUE TITLE
'Serverside' still present in l10n resources...

### ISSUE THREAD

**Issue by silopolis** [R0Wi-DEV/workflow_ocr#194]
… but can't be found in code!?

As I suspect these files to be somehow generated, maybe there could be a bug somewhere… Or I'm just missing something. :)

https://github.com/R0Wi-DEV/workflow_ocr/blob/master/l10n/en_GB.js#L9
https://github.com/R0Wi-DEV/workflow_ocr/blob/master/l10n/en_GB.json#L7

**Comment by R0Wi** [comment]
Think the description in the app metadata is also translated by the NC community but to be honest I don't really know how they make their way to the appstore

**Comment by silopolis** [comment]
OK, but these files are generated here in this repo right?

**Comment by R0Wi** [comment]
Not really, they're synced via Transifex bot, see https://github.com/R0Wi-DEV/workflow_ocr/issues/146 and https://github.com/nextcloud/docker-ci/issues/518 for details.

**Comment by R0Wi** [comment]
Backported to 24/25, should be fixed

**Comment by p-bo** [comment]
> Think the description in the app metadata is also translated by the NC community but to be honest I don't really know how they make their way to the appstore

Currently, they are extracted (which is good progress!), but we are waiting for implementation of writing translations back into metadata - see https://github.com/nextcloud/docker-ci/issues/516
