### ISSUE TITLE
WORKFLOW OCR stopped working NC26 after latest upgrade

### ISSUE THREAD

**Issue by lukaszzyla** [R0Wi-DEV/workflow_ocr#202]
I have a built docker image of nextcloud26:fpm with tesseract in few languages and ocrmypdf built in.
it used to work flawlessly but after last update i only keep seeing:

Error | workflow_ocr | OCR for file /Lukasz/files/WZ THOMAS.pdf not possible. Message: OCRmyPDF did not produce any output |   | 2023-04-13T08:10:00+0200
-- | -- | -- | -- | --
Warning | workflow_ocr | OCRmyPDF succeeded with warning(s): sh: 1: ocrmypdf: not found,

user www-data can use ocrmypdf from cmd inside the container and it generates output.
replicated on another instance brand new install

**Comment by R0Wi** [comment]
Usually a php `fpm` setup consists of two containers, right? One webserver container and the `fpm` container itself, where the php code is executed. Are you sure that the command `ocrmypdf` is available inside of the  `fpm` container for the user running the fpm process? 

And could you share your Docker setup so that we'd be able to reproduce this issue, including `docker-compose` and/or image names, `Dockerfile` etc.?

**Comment by lukaszzyla** [comment]
works like charm again! Thank you so much!!!
swapping cron image to the custom one has made everything work again. I could notice when forcing php cron.php by the waiting time...
How come it used to work before? the most important it is fine again.
Thank you for your work. Ocrmypdf looks to be great tool.
I am currently planning to speed up document delivery by camera scanning and OCRing them in nextcloud. I hope it would be possible to sort them later on, eg by customer or shipper.

**Comment by R0Wi** [comment]
> works like charm again! Thank you so much!!!

Glad to hear that things are working again 👍 

> How come it used to work before? 

Well that's indeed an interesting question. Don't know if you might did some minor changes to your setup but generally speaking: the container which executes the `cron.php` script needs to have `ocrmypdf` installed. That's mandatory 

> I am currently planning to speed up document delivery by camera scanning and OCRing them in nextcloud. I hope it would be possible to sort them later on, eg by customer or shipper.

Sounds interesting. I'm using the OCR app together with the [Full Text Search](https://github.com/nextcloud/fulltextsearch) app and this works quite well when "scanning" documents with my smatphone, uploading them to NC, getting them OCRred and then indexed into the Elasticsearch database

**Comment by lukaszzyla** [comment]
Your extended image looks like a solution to my issues ;-)
How do you solve tesseract-ocr languages in your builds? They should be built in already with ocrmypdf?

**Comment by R0Wi** [comment]
Well currently only German and English are installed (see [here](https://github.com/R0Wi/nextcloud-docker-extended/blob/c2e99afdeb1f691f41862b16b655e1770a85421d/Dockerfile#L6)) but I could extend this of course :+1:

**Comment by lukaszzyla** [comment]
that would be great if you could. my set includes: eng deu fra ita nld pol

**Comment by R0Wi** [comment]
There you go https://hub.docker.com/layers/r0wi/nextcloud-extended/26-apache/images/sha256-eafd163bc18a91855a55a711bf2b52f1aa3c26f21da42dec256c005863b69362?context=explore :rocket:
