### ISSUE TITLE
NC 27.0.0 compatibility

### ISSUE THREAD

**Issue by gmed-ed** [R0Wi-DEV/workflow_ocr#210]
As for now Nextcloud stable reached 27.0.x
Unfortunally workflow_ocr keeps depending on 26.x.x branch.

Would be nice to see a NC 27.0.x compatible version or maybe a hint, 
how to get workflow_ocr running on 27.0.x

many thanks in advance

**Comment by R0Wi** [comment]
Done, see https://github.com/R0Wi-DEV/workflow_ocr/releases/tag/v1.27.0

Appreciate your feedback!

**Comment by gmed-ed** [comment]
Has worked as a charm
Thank you very much and have a nice week
