### ISSUE TITLE
FreeBSD Support?

### ISSUE THREAD

**Issue by DecusAnima** [R0Wi-DEV/workflow_ocr#215]
I recently attempted to install this workflow into a TrueNAS Core jail of Nextcloud. However while I did follow the installation of OCRmyPDF as well as Tesseract the language list of the flow on my Nextcloud site remains empty. 

I imagine this is due to Workflow OCR looking for these apps in where a Linux machine would typically have these programs installed, and TrueNAS Core is FreeBSD. I was curious if you could confirm this, and there is a way for me to get it to get Workflow OCR to see my OCRmyPDF installation in the jail. 

I should mention that both Tesseract and OCRmyPDF seem to be properly installed as I can run their commands manually through the shell and get outputs.

**Comment by R0Wi** [comment]
Hi, the app uses `tesseract --list-langs` to receive the installed languages on the backend system.

https://github.com/R0Wi-DEV/workflow_ocr/blob/98bd3bd6acd43ec5ef38a1ece7de161ab0cdce19/lib/Service/OcrBackendInfoService.php#L47

Could you check if you can execute this command manually on your backend? Also would it be possible for you to share some Nextcloud logs after you opened the settings page and tried to configure the appropriate languages? Otherwise it will be quite hard for us to tell where the error comes from. 

Could you also tell us which version (Nextcloud + app) you're using? We had something similar in https://github.com/R0Wi-DEV/workflow_ocr/issues/184

**Comment by DecusAnima** [comment]
I ran tesseract --list-langs in the jail and got the output showing in the screenshot, I also went ahead and read the attached nextcloud.log and it seems the vast majority was some antivirus errors because I admittedly haven't fully setup. My Nextcloud is running version 27.0.0 and the app is running version 1.27.1.
[nextcloud.log](https://github.com/R0Wi-DEV/workflow_ocr/files/12247944/nextcloud.log)
![tesseract --list-langs](https://github.com/R0Wi-DEV/workflow_ocr/assets/132281597/609f7235-19f7-4eb5-98da-280e92094ec1)

**Comment by R0Wi** [comment]
Thanks for your fast feedback! I'd say that from a backend perspective everything looks good. I could only imagine that you're facing a frontend issue with the OCR workflow settings UI. To check that you should open your browsers [devtools](https://developer.chrome.com/docs/devtools/open/) if possible. After that, please browse to the settings UI and try to open the languages dropdown. If there is an error in the frontend code, it should show up in the [console](https://wordpress.org/documentation/article/using-your-browser-to-diagnose-javascript-errors/#:~:text=Press%20Command%2BOption%2BJ%20(,menu%2C%20and%20click%20Console%20tab.&text=The%20error%20console%20will%20open,errors%20try%20reloading%20the%20page.)) tab. Please share your results here afterwards.

Btw: the OCR workflow should also work fine without a language set, even though the result might not be as accurate.

**Comment by DecusAnima** [comment]
Ah, I found the source of the issue now, seems to be a 404 error with some of the js code for the OCR workflow, followed by error 500 when attempting to pull request the following files. It's possible this might be due to a lack of javascript plugins in my FreeBSD Jail, I'm going to look into that to see. If there is any other ideas you have for this I'd appreciate it.
![Screenshot 2023-08-04 003722](https://github.com/R0Wi-DEV/workflow_ocr/assets/132281597/d22b141f-37c6-4f62-82e3-fea111757e26)

![Screenshot 2023-08-04 003338](https://github.com/R0Wi-DEV/workflow_ocr/assets/132281597/59937079-ab9d-4fed-b5ed-f7cf2203cbf9)

**Comment by R0Wi** [comment]
Yes it indeed seems that the API endpoint which delivers the installed languages (`/apps/workflow_ocr/ocrBackendInfo/installesLangs`) fails with a server error 500. What's weird here is that this error should be logged in the `nextcloud.log` file, don't know why it's not there.

The app itself delivers all Javascripts it needs so there shouldn't be a need of anything else. Could you try to directly browse to `https://192.168.1.40/apps/workflow_ocr/ocrBackendInfo/installesLangs` and see what's the result? Also please again check your NC log for any `workflow_ocr` related entries. You might also try to decrease your [loglevel](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level) if needed.

**Comment by R0Wi** [comment]
Might be a duplicate of https://github.com/R0Wi-DEV/workflow_ocr/issues/183

**Comment by DecusAnima** [comment]
Going to https://192.168.1.40/apps/workflow_ocr/ocrBackendInfo/installesLangs directly gives a page not found error with the following console log.
![Screenshot 2023-08-04 020835](https://github.com/R0Wi-DEV/workflow_ocr/assets/132281597/f1445b2b-8062-41ab-8aaa-0c806ca7f6c7)
Reducing loglevel to 0 did produce some issues regarding /appinfo/app.php, but I'm not sure if this is the cause, unfortunately the log file is getting so large that I couldn't upload it. That being said nothing outside of the following line from the log doesn't seem to be in reference to OCR.

00:00","remoteAddr":"192.168.1.10","user":"DecusAnima","app":"encryption","method":"GET","url":"/apps/workflow_ocr/ocrBackendInfo/installedLangs","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36","version":"27.0.0.8","data":{"app":"encryption"}}
{"reqId":"tiqw5igzNCOBIqlk32JF","level":0,"time":"2023-08-04T07:15:59+

**Comment by R0Wi** [comment]
Sorry I had a typo in my url, I meant  https://192.168.1.40/apps/workflow_ocr/ocrBackendInfo/installedLangs. You can also copy the url directly from your browser console where you got the 500 error.

**Comment by DecusAnima** [comment]
Seemed to have found the issue, going to the corrected link gives a CSRF check fail, wouldn't know if this has to do with OCR workflow or Tesseract though.

**Comment by R0Wi** [comment]
Ah sorry I think directly calling the endpoint is not possible due to the automatic [CSRF check](https://docs.nextcloud.com/server/23/developer_manual/prologue/security.html#cross-site-request-forgery).

If you're on the settings page and open the devtools, could you please try to query the following in the `console` tab?

```js
$.get('https://192.168.1.40/index.php/apps/workflow_ocr/ocrBackendInfo/installedLangs').then(res=>console.log(res))
```

I'd like to get more information on the 500 server error, either through the logs or through the frontend

**Comment by DecusAnima** [comment]
![Screenshot 2023-08-04 040517](https://github.com/R0Wi-DEV/workflow_ocr/assets/132281597/31bc7cd7-6c45-4f2b-9472-5045412d8671)

**Comment by DecusAnima** [comment]
Logs still seems to only show the /appinfo/app.php deprecation when referencing the https://192.168.1.40/index.php/apps/workflow_ocr/ocrBackendInfo/installedLangs pull

**Comment by R0Wi** [comment]
It has to be a really "hard" error if it's not logged in the `nextcloud.log`. Maybe you want to also check your webserver and/or php log files if possible.

What does the following give you?

```js
$.get('https://192.168.1.40/index.php/apps/workflow_ocr/ocrBackendInfo/installedLangs').error(res=>console.log(res.responseText)).then(res=>console.log(res))
```

This should log the returned HTML page the server gives you

**Comment by DecusAnima** [comment]
![Screenshot 2023-08-04 044125](https://github.com/R0Wi-DEV/workflow_ocr/assets/132281597/c71452bc-bb5c-4957-8cb7-3f5fe94a2b9d)
Couldn't find anything relevant in php logs. As for the pull results, looks like that bash can't see Tesseract.

**Comment by DecusAnima** [comment]
Wow, after a few hours of messing with permissions and pathing, I finally got it. I guess the issue did indeed stem from where FreeBSD set the PATH variables, I had to dig through some forums to find how to add new commands to the list but afterwards the languages popped up. Thank you for guiding me through this.

**Comment by DecusAnima** [comment]
It seems another issue is cropping up however, once I had everything set up when I try to save a flow I get the following
![Screenshot 2023-08-04 071421](https://github.com/R0Wi-DEV/workflow_ocr/assets/132281597/14a47e71-938f-43a4-89cb-4fe04ada513a)

**Comment by R0Wi** [comment]
Glad to help! I think you're facing the same issue like mentioned here: https://github.com/R0Wi-DEV/workflow_ocr/issues/41

Btw: if you provide the full solution on how you fixed the error, I'd be happy to but some notes into the README.

**Comment by DecusAnima** [comment]
Yeah I found the resolution for the above error quickly with the mentioned issue, thanks again.

For a full solution regarding this error, apparently it has to do with the user running the php and/or web programs for Nextcloud not having the path for tesseract commands. In my case the bin for tesseract was in /usr/local/bin. FreeBSD has a command for routing a new command path 'chsh' (e.g. chsh -s /usr/local/bin/tesseract).
