### ISSUE TITLE
Manual application of rule to any file

### ISSUE THREAD

**Issue by ostasevych** [R0Wi-DEV/workflow_ocr#218]
Hi! Would that be possible to build a new app on the base of this one which will allow to apply the rule to any selected file(s) in Files app? So, when I select one or more files, click context menu button and select the operation to OCR files, and this will apply the rule towards them?

**Comment by R0Wi** [comment]
This is already discussed in https://github.com/R0Wi-DEV/workflow_ocr/discussions/198. Please feel free to add your input there. 

What needs to be mentioned here is that the infrastructure of workflow apps is not designed to cover such a usecase. Therefore the implementation of such a feature would be rather time consuming and we currently do not have the capacity to realize this.

As a temporary workaround you could try a "tag assigned" approach like described [here](https://github.com/R0Wi-DEV/workflow_ocr#trigger-ocr-on-tag-assigning). This would add a file to the queue if you assigned a certain tag to it. Nevertheless the actual processing would still be asynchronous via NC cron.
