### ISSUE TITLE
Trigger OCR if file was created or updated is not working 

### ISSUE THREAD

**Issue by lodzen** [R0Wi-DEV/workflow_ocr#241]
**Describe the bug**

Trigger OCR if file was created or updated is not working 

**System**

- App version: 1.28
- Nextcloud version: 28.0.1
- PHP version: 8.2.13
- Environment: [Docker/native Apache/native PHP FPM/...]
Linux 6.1.0-rpi7-rpi-2712 aarch64
Docker Compose from Linuxserver
- `ocrmypdf` version: 14.1.0-r1

**How to reproduce**

Configure the Workflow as mentioned in the manual
The OCR is not triggered by Nextcloud if a file was added or modified.

**Screenshots**

Conversion is only working for Tags
Reason why the ocr Tag is added multiple times is because the automated tagging workflow is used on top
![image](https://github.com/R0Wi-DEV/workflow_ocr/assets/21340840/b9012ef1-a541-4ed2-be53-7ab64a6b0ede)

**Server log**

Please paste relevant content of your [ `nextcloud.log`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#logging) file here.  It might make sense to first decrease the [Loglevel](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level). Also, since the OCR process runs asynchronously, run your [cron.php](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron) before copying the logs here.

```
Nothing visible in the server log files
```

**Comment by R0Wi** [comment]
Thanks for reporting this. Unfortunately I cannot reproduce the issue. Here is what I did: 

1. Create a fresh NC 28 Docker instance
2. Install the Workflow OCR app from the Appstore
3. Install `ocrmypdf` inside of the container
4. Configure a personal flow like this (to ensure it will always be processed via OCR):
![image](https://github.com/R0Wi-DEV/workflow_ocr/assets/19730957/361440b7-01b8-4cb9-b8bb-6d27fbe9fb7d)
5. Upload the following test file: [ocr-test.pdf](https://github.com/R0Wi-DEV/workflow_ocr/files/14020604/ocr-test.pdf) via NC UI
6. Trigger the NC cron `sudo -u www-data php cron.php` 

Result: new file version is created as expected, text is markable inside of the document

![image](https://github.com/R0Wi-DEV/workflow_ocr/assets/19730957/33e7872d-23ba-4ae7-a1ac-5914dc446f1c)

Please use our [troubleshooting guide](https://github.com/R0Wi-DEV/workflow_ocr?tab=readme-ov-file#troubleshooting) and repeat your process. If you decreased your logging level like described, there must be some server logs. Those are mandatory for us to understand the problem.

Thanks for your help

**Comment by lodzen** [comment]
Hello,

i setup the flow exactly as in your screenshot:
![image](https://github.com/R0Wi-DEV/workflow_ocr/assets/21340840/512eda94-acef-405b-9493-e7824b73e9c9)

The cron is configured to run all 5min:
![image](https://github.com/R0Wi-DEV/workflow_ocr/assets/21340840/ff430189-fc53-46c8-9f5c-e32e1ee7a07c)

Test pdf:
![image](https://github.com/R0Wi-DEV/workflow_ocr/assets/21340840/df7ccc78-b3a7-4698-8c5b-c52c3f9e0294)

Even after 15 min file was not analyzed:
![image](https://github.com/R0Wi-DEV/workflow_ocr/assets/21340840/3f746b73-5874-4015-b052-5b784d0796ef)

![image](https://github.com/R0Wi-DEV/workflow_ocr/assets/21340840/1de32331-7e7d-486e-bf2c-6d9f07499bd7)


The difference is that its not a personal flow at my end its a global one

**Comment by lodzen** [comment]
Ok but even with a personal flow the Job is not executed

**Comment by R0Wi** [comment]
Your frontend configuration looks correct. Nevertheless, without additional backend logs it will be impossible to find the error. Like described [here](https://github.com/R0Wi-DEV/workflow_ocr?tab=readme-ov-file#troubleshooting), please decrease your NC loglevel, repeat the process (don't forget to execute the cron manually) and post your logs here.

**Comment by lodzen** [comment]
I created the logs now and tried to prefilter it as best as possible
[flow.log](https://github.com/R0Wi-DEV/workflow_ocr/files/14049939/flow.log)
[nextcloud.log](https://github.com/R0Wi-DEV/workflow_ocr/files/14049940/nextcloud.log)

**Comment by R0Wi** [comment]
There are two interesting lines in your `nextcloud.log`, one is logged by the `workflowengine` itself and the other is logged by this app (`workflow_ocr`):

```json
{"reqId":"jiLiFxRBg9xJAAFAsV97","level":0,"time":"2024-01-25T09:32:59+00:00","remoteAddr":"79.249.68.60","user":"daniel","app":"workflowengine","method":"GET","url":"/core/preview?fileId=11909&x=250&y=250","message":"No flow configurations is going to run OCR-Datei","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.1.1","data":{"app":"workflowengine","level":"0"},"id":196}

{"reqId":"jiLiFxRBg9xJAAFAsV97","level":0,"time":"2024-01-25T09:32:59+00:00","remoteAddr":"79.249.68.60","user":"daniel","app":"workflow_ocr","method":"GET","url":"/core/preview?fileId=11909&x=250&y=250","message":"Not processing event because IRuleMatcher->getFlows did not return anything","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.1.1","data":{"app":"workflow_ocr"},"id":197}
```

I think the interesting bit here is `No flow configurations is going to run OCR-Datei`, which tells us that there might be some misconfiguration in your workflow. The second line tells us basically the same `Not processing event because IRuleMatcher->getFlows did not return anything`.

![image](https://github.com/R0Wi-DEV/workflow_ocr/assets/19730957/563b82cf-593d-4980-879b-4a1964e18710)

At the moment I have no idea why it behaves like this for you but it doesn't seem to be a general problem with Nextcloud 28 since I can't reproduce the problem. I think further investigation is needed here.

If you setup a workflow with the same conditions (file created/updated, mimetype is PDF) and you use the "Workflow Tagging", does this one work? So will it tag your PDF files correctly?

**Comment by R0Wi** [comment]
Some technical details:

* The "Flow activation: rules were requested for operation OCR-Datei" log messages is written [here](https://github.com/nextcloud/server/blob/063c051cdcfbaf1f623337f6f1239438b35d094c/apps/workflowengine/lib/Service/RuleMatcher.php#L143)
* The "No flow configurations is going to run OCR-Datei" message is written [here](https://github.com/nextcloud/server/blob/063c051cdcfbaf1f623337f6f1239438b35d094c/apps/workflowengine/lib/Service/RuleMatcher.php#L213)

Both log messages are produced by the `workflowengine` of Nextcloud, which contains the core-logic for workflow apps. In this case the [`getFlows`](https://github.com/nextcloud/server/blob/063c051cdcfbaf1f623337f6f1239438b35d094c/apps/workflowengine/lib/Service/RuleMatcher.php#L124)  method is called by our `workflow_ocr` app and the core logic of Nextcloud tells the app to "not run".

**Comment by R0Wi** [comment]
Seems to be an NC core related issue. Feel free to raise this [here](https://github.com/nextcloud/server/issues). Closed due to lack of feedback.
