### ISSUE TITLE
Enable PHP8.3 support

### ISSUE THREAD

**Issue by Rexaris** [R0Wi-DEV/workflow_ocr#251]
As NC28 enables PHP8.3 support and NC29 recommends PHP8.3 (https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html) 
it would be cool to see support also for your app.

(See PHP8.2 issue: https://github.com/R0Wi-DEV/workflow_ocr/issues/191)

**Comment by R0Wi** [comment]
Confirm that this should be added. We will work on it

**Comment by R0Wi** [comment]
Fixed with `v1.28.1`. Added to NC28 only since the version for NC29 already had PHP 8.3 support.
