### ISSUE TITLE
the actions "rename" and "access" do not trigger the OCR scan

### ISSUE THREAD

**Issue by ferdiga** [R0Wi-DEV/workflow_ocr#257]
**Describe the bug**

Create and copy trigger the OCR Workflow process, rename and access do not trigger the OCR Workflow process

**System**

- App version: 1.29
- Nextcloud version: Nextcloud AIO v9.2.0
- PHP version: [VERSION]
- Environment: [Docker/native Apache/native PHP FPM/...]
- `ocrmypdf` version: 16.1.1 (inside the nextcloud-aio-nextcloud container)

**How to reproduce**

1. open or rename a pdf file without text layer
2. wait (endless)
3. OCR workflow is not triggered and OCR Tag is not set

**Screenshots**
OCR Workflow config
<img width="417" alt="20240723 115115 Flow - Administration settings - Nextcloud" src="https://github.com/user-attachments/assets/e256a49b-1d24-47e5-b0f2-995c35a27a71">

File after renaming and copy, renamed file is not OCR scanned
<img width="392" alt="20240723 115307 Files - Nextcloud" src="https://github.com/user-attachments/assets/e9d67362-e831-43e1-966e-7716b1a4fbb7">

**Server log**

Please paste relevant content of your [ `nextcloud.log`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#logging) file here.  It might make sense to first decrease the [Loglevel](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level). Also, since the OCR process runs asynchronously, run your [cron.php](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron) before copying the logs here.

```
NC log - 
[workflow_ocr] Warning: Tesseract list languages succeeded with warning(s): [DS] Profile read from file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 0:(null) score is 0.670627
[DS] Selected Device[1]: "(null)" (Native), 
	GET /apps/workflow_ocr/ocrBackendInfo/installedLangs
	from xxx.xxx.xxx.xxx by gass at Jul 23, 2024, 11:38:50 AM
```
BTW it would be helpful to include the name of the  processed file to be sure which file caused the message

**Browser log**

```
Paste your developer tools logs here. 
```

**Additional context**

**Comment by R0Wi** [comment]
Hi, in your log snippet I cannot see anything like `STARTED -- Run ...`. This line should be printed if the OCR workflow gets kicked off and your loglevel is set to `DEBUG` (0). Could you please refer to [this guide](https://github.com/R0Wi-DEV/workflow_ocr?tab=readme-ov-file#generic-troubleshooting-guide) and repeat your steps once again? This would help us in seeing what's going on under the hood.

**Comment by ferdiga** [comment]
<img width="377" alt="20240723 133626 Logging - Administration settings - Nextcloud" src="https://github.com/user-attachments/assets/36d16061-d385-4b26-8285-bdaa68f90818">

renaming a file  - does this help
