### ISSUE TITLE
OCR Flow should handle digitally signed files in a smart way

### ISSUE THREAD

**Issue by ferdiga** [R0Wi-DEV/workflow_ocr#258]
digitally signed files are omitted by ocrmypdf - which is a possible correct behaviour.

as exactly these might be off high interest I suggest to optionally create a separate file (<filename>-OCR.pdf) and leave the original signed file as it is.

**System**

- App version: 1.29.0
- Nextcloud version: AIO - 9.3.0
- PHP version: [VERSION]
- Environment: [Docker/native Apache/native PHP FPM/...]
- `ocrmypdf` version: [VERSION] 

**How to reproduce**

**Screenshots**

**Server log**

Please paste relevant content of your [ `nextcloud.log`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#logging) file here.  It might make sense to first decrease the [Loglevel](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level). Also, since the OCR process runs asynchronously, run your [cron.php](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron) before copying the logs here.

```
Paste relevant server log lines here. Make sure to trim sensitive information.
```

**Browser log**

If you're observing Browser errors, please paste your developer tools logs here. 

Help for Chrome: https://developer.chrome.com/docs/devtools/console/#view
Help for Firefox: https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html

```
Paste your developer tools logs here. 
```

**Additional context**

**Comment by R0Wi** [comment]
Please use https://github.com/R0Wi-DEV/workflow_ocr/issues/220 for further discussion
