### ISSUE TITLE
somehow report back errors to user?

### ISSUE THREAD

**Issue by mortee** [R0Wi-DEV/workflow_ocr#89]
I started experimenting with this app, and while the potential seems to be quite great, more often than not my docs don't get OCR processed, and I have no idea why. Experimenting with ocrmypdf directly shows that it can be quite picky - e.g. when I feed it a big JPG which lies to be 72 dpi then ocrmypdf gets suspicious and drops the file. However, it can scan it just fine if I specify a correct dpi setting. 

It would be nice if such errors would be reported back to the user. What comes to mind is leaving a comment on the file, and/or sending a Talk message.

**Comment by R0Wi** [comment]
Sounds like a good idea to me. Btw we are also working on applying different OCR settings per workflow so the dpi setting could be one of those.

**Comment by mortee** [comment]
That was just an example, the point is that one can have no idea what's happening in the background, and there seem to be a lot of different reasons for it to go wrong.

Anyway, is there a method to closely trace what the workflow engine is doing? I checked the documentation, googed a lot, asked in various forums, but couldn't figure it out. `occ config:app:set workflowengine logfile` apparently has no effect, I still have an empty flow.log.

**Comment by R0Wi** [comment]
Well yes the OCR app writes to the `nextcloud.log` file. Depending on your configured loglevel you will see various logmessages when the OCR process runs. As admin you could also use the logviewer of NC to show and filter these messages. If the process returns an error a logmessage with level `error` will be logged.

**Comment by mortee** [comment]
> occ config:app:set workflowengine logfile

OK so this definitely has no effect?

**Comment by R0Wi** [comment]
Good question, at least it's not directly related to this app even though it's a workflow app. So no this does not directly affect this app.

**Comment by mortee** [comment]
Yeah, that part is clear. Just I have no clue where to ask about generic workflow debugging.

**Comment by R0Wi** [comment]
Sorry didn't get it 😄 Basically the workflow engine is part of nextcloud server core (https://github.com/nextcloud/server) so you could ask there. But like i said a workflow app is just a special kind of NC app so it highly depends on the app itself regarding logging.

For this app here i'm looking forward to implement the comment function if the OCR process failed, like you described 👍
